import { DATA_VERSION, defaultDashboardLayout } from "./constants.js";

export function createEmptyState() {
  return {
    version: DATA_VERSION,
    fxRate: {
      pair: "USD/KRW",
      rate: 1350,
      previousClose: 1350,
      change: 0,
      changePercent: 0,
      source: "기본 환율",
      asOf: "가격 업데이트 전",
    },
    holdings: [],
    cashFlows: [],
    cashBalances: [],
    accounts: [],
    dashboardLayout: structuredClone(defaultDashboardLayout),
    accountSnapshots: [],
    priceUpdateLogs: [],
    lastPriceRefreshImpact: null,
    portfolioSnapshots: [],
    automation: {
      lastRunAt: null,
      lastResult: "아직 자동 실행 없음",
      snapshotTime: "09:10",
      timezone: "Asia/Seoul",
    },
  };
}

export function createSampleState(makeId) {
  return {
    version: DATA_VERSION,
    fxRate: {
      pair: "USD/KRW",
      rate: 1350,
      previousClose: 1342,
      change: 8,
      changePercent: 0.00596,
      source: "샘플 환율",
      asOf: "샘플",
    },
    holdings: [
      {
        id: makeId(),
        investor: "투자자 A",
        account: "연금 계좌",
        accountType: "pension",
        strategy: "QQQ",
        ticker: "QQQ",
        name: "Invesco QQQ Trust",
        quantity: 18,
        averageCost: 408.25,
        price: 430.15,
        priceChange: 3.24,
        priceChangePercent: 0.0076,
        currency: "USD",
        priceSource: "샘플",
        priceAsOf: "샘플",
      },
      {
        id: makeId(),
        investor: "투자자 A",
        account: "일반 계좌",
        accountType: "direct_investment",
        strategy: "기타",
        ticker: "MSFT",
        name: "Microsoft",
        quantity: 12,
        averageCost: 375.4,
        price: 414.92,
        priceChange: -2.18,
        priceChangePercent: -0.0052,
        currency: "USD",
        priceSource: "샘플",
        priceAsOf: "샘플",
      },
      {
        id: makeId(),
        investor: "투자자 B",
        account: "일반 계좌",
        accountType: "direct_investment",
        strategy: "기타",
        ticker: "NVDA",
        name: "NVIDIA",
        quantity: 20,
        averageCost: 104.5,
        price: 128.4,
        priceChange: 4.36,
        priceChangePercent: 0.0351,
        currency: "USD",
        priceSource: "샘플",
        priceAsOf: "샘플",
      },
      {
        id: makeId(),
        investor: "투자자 B",
        account: "코어 계좌",
        accountType: "direct_investment",
        strategy: "S&P500",
        ticker: "VOO",
        name: "Vanguard S&P 500 ETF",
        quantity: 10,
        averageCost: 465.2,
        price: 510.75,
        priceChange: 1.42,
        priceChangePercent: 0.0028,
        currency: "USD",
        priceSource: "샘플",
        priceAsOf: "샘플",
      },
      {
        id: makeId(),
        investor: "투자자 A",
        account: "전술 계좌",
        accountType: "direct_investment",
        strategy: "S&P500",
        ticker: "SSO",
        name: "ProShares Ultra S&P500",
        quantity: 35,
        averageCost: 58.4,
        price: 64.1,
        priceChange: -0.84,
        priceChangePercent: -0.0129,
        currency: "USD",
        priceSource: "샘플",
        priceAsOf: "샘플",
      },
    ],
    cashFlows: [
      {
        id: makeId(),
        date: "2026-05-10",
        investor: "투자자 A",
        account: "연금 계좌",
        type: "deposit",
        amountKrw: 1200000,
        note: "월 납입",
      },
      {
        id: makeId(),
        date: "2026-05-12",
        investor: "투자자 B",
        account: "일반 계좌",
        type: "deposit",
        amountKrw: 800000,
        note: "추가입금",
      },
    ],
    cashBalances: [],
    accounts: [],
    dashboardLayout: structuredClone(defaultDashboardLayout),
    accountSnapshots: [],
    priceUpdateLogs: [],
    lastPriceRefreshImpact: null,
    portfolioSnapshots: [
      {
        id: makeId(),
        date: "2026-05-10",
        totalValueUsd: 24850,
        totalValueKrw: 33547500,
        totalCostUsd: 23400,
        totalGainUsd: 1450,
        fxRate: 1350,
        netInflowKrw: 1200000,
      },
      {
        id: makeId(),
        date: "2026-05-11",
        totalValueUsd: 25140,
        totalValueKrw: 33939000,
        totalCostUsd: 23400,
        totalGainUsd: 1740,
        fxRate: 1350,
        netInflowKrw: 0,
      },
      {
        id: makeId(),
        date: "2026-05-12",
        totalValueUsd: 26010,
        totalValueKrw: 35113500,
        totalCostUsd: 23990,
        totalGainUsd: 2020,
        fxRate: 1350,
        netInflowKrw: 800000,
      },
      {
        id: makeId(),
        date: "2026-05-13",
        totalValueUsd: 25920,
        totalValueKrw: 34992000,
        totalCostUsd: 23990,
        totalGainUsd: 1930,
        fxRate: 1350,
        netInflowKrw: 0,
      },
      {
        id: makeId(),
        date: "2026-05-14",
        totalValueUsd: 26420,
        totalValueKrw: 35667000,
        totalCostUsd: 23990,
        totalGainUsd: 2430,
        fxRate: 1350,
        netInflowKrw: 0,
      },
    ],
    automation: {
      lastRunAt: null,
      lastResult: "아직 자동 실행 없음",
      snapshotTime: "09:10",
      timezone: "Asia/Seoul",
    },
  };
}
